
import { TarotCard, SpreadType, SpreadInfo } from './types';

export const TAROT_DECK: TarotCard[] = [
  // Major Arcana
  { id: 0, name: 'The Fool', name_tw: '愚者', arcana: 'Major' },
  { id: 1, name: 'The Magician', name_tw: '魔術師', arcana: 'Major' },
  { id: 2, name: 'The High Priestess', name_tw: '女祭司', arcana: 'Major' },
  { id: 3, name: 'The Empress', name_tw: '皇后', arcana: 'Major' },
  { id: 4, name: 'The Emperor', name_tw: '皇帝', arcana: 'Major' },
  { id: 5, name: 'The Hierophant', name_tw: '教皇', arcana: 'Major' },
  { id: 6, name: 'The Lovers', name_tw: '戀人', arcana: 'Major' },
  { id: 7, name: 'The Chariot', name_tw: '戰車', arcana: 'Major' },
  { id: 8, name: 'Strength', name_tw: '力量', arcana: 'Major' },
  { id: 9, name: 'The Hermit', name_tw: '隱者', arcana: 'Major' },
  { id: 10, name: 'Wheel of Fortune', name_tw: '命運之輪', arcana: 'Major' },
  { id: 11, name: 'Justice', name_tw: '正義', arcana: 'Major' },
  { id: 12, name: 'The Hanged Man', name_tw: '倒吊人', arcana: 'Major' },
  { id: 13, name: 'Death', name_tw: '死神', arcana: 'Major' },
  { id: 14, name: 'Temperance', name_tw: '節制', arcana: 'Major' },
  { id: 15, name: 'The Devil', name_tw: '惡魔', arcana: 'Major' },
  { id: 16, name: 'The Tower', name_tw: '塔', arcana: 'Major' },
  { id: 17, name: 'The Star', name_tw: '星星', arcana: 'Major' },
  { id: 18, name: 'The Moon', name_tw: '月亮', arcana: 'Major' },
  { id: 19, name: 'The Sun', name_tw: '太陽', arcana: 'Major' },
  { id: 20, name: 'Judgement', name_tw: '審判', arcana: 'Major' },
  { id: 21, name: 'The World', name_tw: '世界', arcana: 'Major' },
  // Wands (權杖)
  { id: 22, name: 'Ace of Wands', name_tw: '權杖王牌', arcana: 'Minor', suit: 'Wands' },
  { id: 23, name: 'Two of Wands', name_tw: '權杖二', arcana: 'Minor', suit: 'Wands' },
  { id: 24, name: 'Three of Wands', name_tw: '權杖三', arcana: 'Minor', suit: 'Wands' },
  { id: 25, name: 'Four of Wands', name_tw: '權杖四', arcana: 'Minor', suit: 'Wands' },
  { id: 26, name: 'Five of Wands', name_tw: '權杖五', arcana: 'Minor', suit: 'Wands' },
  { id: 27, name: 'Six of Wands', name_tw: '權杖六', arcana: 'Minor', suit: 'Wands' },
  { id: 28, name: 'Seven of Wands', name_tw: '權杖七', arcana: 'Minor', suit: 'Wands' },
  { id: 29, name: 'Eight of Wands', name_tw: '權杖八', arcana: 'Minor', suit: 'Wands' },
  { id: 30, name: 'Nine of Wands', name_tw: '權杖九', arcana: 'Minor', suit: 'Wands' },
  { id: 31, name: 'Ten of Wands', name_tw: '權杖十', arcana: 'Minor', suit: 'Wands' },
  { id: 32, name: 'Page of Wands', name_tw: '權杖侍者', arcana: 'Minor', suit: 'Wands' },
  { id: 33, name: 'Knight of Wands', name_tw: '權杖騎士', arcana: 'Minor', suit: 'Wands' },
  { id: 34, name: 'Queen of Wands', name_tw: '權杖皇后', arcana: 'Minor', suit: 'Wands' },
  { id: 35, name: 'King of Wands', name_tw: '權杖國王', arcana: 'Minor', suit: 'Wands' },
  // Cups (聖杯)
  { id: 36, name: 'Ace of Cups', name_tw: '聖杯王牌', arcana: 'Minor', suit: 'Cups' },
  { id: 37, name: 'Two of Cups', name_tw: '聖杯二', arcana: 'Minor', suit: 'Cups' },
  { id: 38, name: 'Three of Cups', name_tw: '聖杯三', arcana: 'Minor', suit: 'Cups' },
  { id: 39, name: 'Four of Cups', name_tw: '聖杯四', arcana: 'Minor', suit: 'Cups' },
  { id: 40, name: 'Five of Cups', name_tw: '聖杯五', arcana: 'Minor', suit: 'Cups' },
  { id: 41, name: 'Six of Cups', name_tw: '聖杯六', arcana: 'Minor', suit: 'Cups' },
  { id: 42, name: 'Seven of Cups', name_tw: '聖杯七', arcana: 'Minor', suit: 'Cups' },
  { id: 43, name: 'Eight of Cups', name_tw: '聖杯八', arcana: 'Minor', suit: 'Cups' },
  { id: 44, name: 'Nine of Cups', name_tw: '聖杯九', arcana: 'Minor', suit: 'Cups' },
  { id: 45, name: 'Ten of Cups', name_tw: '聖杯十', arcana: 'Minor', suit: 'Cups' },
  { id: 46, name: 'Page of Cups', name_tw: '聖杯侍者', arcana: 'Minor', suit: 'Cups' },
  { id: 47, name: 'Knight of Cups', name_tw: '聖杯騎士', arcana: 'Minor', suit: 'Cups' },
  { id: 48, name: 'Queen of Cups', name_tw: '聖杯皇后', arcana: 'Minor', suit: 'Cups' },
  { id: 49, name: 'King of Cups', name_tw: '聖杯國王', arcana: 'Minor', suit: 'Cups' },
  // Swords (寶劍)
  { id: 50, name: 'Ace of Swords', name_tw: '寶劍王牌', arcana: 'Minor', suit: 'Swords' },
  { id: 51, name: 'Two of Swords', name_tw: '寶劍二', arcana: 'Minor', suit: 'Swords' },
  { id: 52, name: 'Three of Swords', name_tw: '寶劍三', arcana: 'Minor', suit: 'Swords' },
  { id: 53, name: 'Four of Swords', name_tw: '寶劍四', arcana: 'Minor', suit: 'Swords' },
  { id: 54, name: 'Five of Swords', name_tw: '寶劍五', arcana: 'Minor', suit: 'Swords' },
  { id: 55, name: 'Six of Swords', name_tw: '寶劍六', arcana: 'Minor', suit: 'Swords' },
  { id: 56, name: 'Seven of Swords', name_tw: '寶劍七', arcana: 'Minor', suit: 'Swords' },
  { id: 57, name: 'Eight of Swords', name_tw: '寶劍八', arcana: 'Minor', suit: 'Swords' },
  { id: 58, name: 'Nine of Swords', name_tw: '寶劍九', arcana: 'Minor', suit: 'Swords' },
  { id: 59, name: 'Ten of Swords', name_tw: '寶劍十', arcana: 'Minor', suit: 'Swords' },
  { id: 60, name: 'Page of Swords', name_tw: '寶劍侍者', arcana: 'Minor', suit: 'Swords' },
  { id: 61, name: 'Knight of Swords', name_tw: '寶劍騎士', arcana: 'Minor', suit: 'Swords' },
  { id: 62, name: 'Queen of Swords', name_tw: '寶劍皇后', arcana: 'Minor', suit: 'Swords' },
  { id: 63, name: 'King of Swords', name_tw: '寶劍國王', arcana: 'Minor', suit: 'Swords' },
  // Pentacles (錢幣)
  { id: 64, name: 'Ace of Pentacles', name_tw: '錢幣王牌', arcana: 'Minor', suit: 'Pentacles' },
  { id: 65, name: 'Two of Pentacles', name_tw: '錢幣二', arcana: 'Minor', suit: 'Pentacles' },
  { id: 66, name: 'Three of Pentacles', name_tw: '錢幣三', arcana: 'Minor', suit: 'Pentacles' },
  { id: 67, name: 'Four of Pentacles', name_tw: '錢幣四', arcana: 'Minor', suit: 'Pentacles' },
  { id: 68, name: 'Five of Pentacles', name_tw: '錢幣五', arcana: 'Minor', suit: 'Pentacles' },
  { id: 69, name: 'Six of Pentacles', name_tw: '錢幣六', arcana: 'Minor', suit: 'Pentacles' },
  { id: 70, name: 'Seven of Pentacles', name_tw: '錢幣七', arcana: 'Minor', suit: 'Pentacles' },
  { id: 71, name: 'Eight of Pentacles', name_tw: '錢幣八', arcana: 'Minor', suit: 'Pentacles' },
  { id: 72, name: 'Nine of Pentacles', name_tw: '錢幣九', arcana: 'Minor', suit: 'Pentacles' },
  { id: 73, name: 'Ten of Pentacles', name_tw: '錢幣十', arcana: 'Minor', suit: 'Pentacles' },
  { id: 74, name: 'Page of Pentacles', name_tw: '錢幣侍者', arcana: 'Minor', suit: 'Pentacles' },
  { id: 75, name: 'Knight of Pentacles', name_tw: '錢幣騎士', arcana: 'Minor', suit: 'Pentacles' },
  { id: 76, name: 'Queen of Pentacles', name_tw: '錢幣皇后', arcana: 'Minor', suit: 'Pentacles' },
  { id: 77, name: 'King of Pentacles', name_tw: '錢幣國王', arcana: 'Minor', suit: 'Pentacles' },
];

export const SPREAD_CONFIG: Record<SpreadType, SpreadInfo> = {
  [SpreadType.SINGLE]: {
    name_en: 'Single Card',
    name_tw: '單張牌',
    cardCount: 1,
    description_en: 'Suitable for Yes/No questions, daily guidance, or simple inquiries.',
    description_tw: '適合是非問題、每日指引或簡單的小問題。',
    positions_en: ['Core Guidance'],
    positions_tw: ['核心指引']
  },
  [SpreadType.THREE_CARD]: {
    name_en: 'Three Cards',
    name_tw: '三張牌',
    cardCount: 3,
    description_en: 'Very common! Often represents "Past/Present/Future", "Strengths/Weaknesses/Advice", or "Self/Other/Outcome".',
    description_tw: '最常見的牌陣！通常代表「過去／現在／未來」、「優點／缺點／建議」或「自己／對方／結果」等。',
    positions_en: ['Past Influence', 'Current Situation', 'Future Trend'],
    positions_tw: ['過去的影響', '現在的狀況', '未來的趨勢']
  },
  [SpreadType.CELTIC_CROSS]: {
    name_en: 'Celtic Cross',
    name_tw: '凱爾特十字牌陣',
    cardCount: 10,
    description_en: 'The most classic and in-depth spread. Shows overall situation, background, future development, internal/external factors, etc.',
    description_tw: '最經典且深入的牌陣，可看整體狀況、問題背景、未來發展、內在外在因素等。',
    positions_en: [
      'Core Situation', 'Immediate Challenge', 'Foundation (Past)', 'Recent Past', 
      'Possible Best Outcome', 'Near Future', 'Your Attitude', 'External Environment', 
      'Hopes and Fears', 'Final Outcome'
    ],
    positions_tw: [
      '核心狀況', '眼前的挑戰', '過去的根基', '近期的過去', 
      '可能的最佳結果', '不久的將來', '你的態度', '環境影響', 
      '希望與恐懼', '最終結果'
    ]
  },
};
